// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsMyers")>]
[<assembly: AssemblyProductAttribute("FsMyers")>]
[<assembly: AssemblyDescriptionAttribute("FSharp implementation of Eugene W. Myers's O(ND) difference algorithm")>]
[<assembly: AssemblyVersionAttribute("0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsMyers"
    let [<Literal>] AssemblyProduct = "FsMyers"
    let [<Literal>] AssemblyDescription = "FSharp implementation of Eugene W. Myers's O(ND) difference algorithm"
    let [<Literal>] AssemblyVersion = "0.1"
    let [<Literal>] AssemblyFileVersion = "0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
